# build environment
FROM node:lts-alpine as build
# Set working directory for the app
WORKDIR /usr/src/app
# Copy local files to app folder
COPY . .
# Install pnpm
RUN npm install -g pnpm
# Install app dependencies and build
RUN pnpm i
RUN pnpm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]